### ISSUE TITLE
Listar camisetas

### ISSUE THREAD

**Issue by Fealps** [murilo-dan/PI2-Vending-Machine#10]

**Comment by beatrizSO** [comment]
**Como** usuário
**Quero** visualizar as camisetas disponíveis
**Para** escolher qual comprar

Critérios de aceitação:

- [ ] Deve listar apenas as camisetas disponíves para a compra no painel apresentando respectivo o nome/título e imagem;

**Comment by mardntas** [comment]
Foi feita junto da issue #16 
Ambas as issues dizem respeito ao cadastro de camiseta e listage mde camiseta via API
