### ISSUE TITLE
Selecionar camiseta

### ISSUE THREAD

**Issue by mardntas** [murilo-dan/PI2-Vending-Machine#12]
Eu, com usuário, desejo selecionar uma camiseta para ver mais informaçoes sober o produto

**Comment by beatrizSO** [comment]
**Como** usuário
**Quero** selecionar uma camiseta
**Para** ver mais informações sobre o produto

Critérios de aceitação:

- [ ] Deve permitir selecionar determinada camiseta;
- [ ] Deve permitir visualizar as informações da mesma:
- Imagem
- Descrição
- Tamanho
- Cor
- Preço
