### ISSUE TITLE
Cadastrar novas camisetas

### ISSUE THREAD

**Issue by Fealps** [murilo-dan/PI2-Vending-Machine#8]
Eu como desenvolvedor desejo receber os dados para cadastrar novas camisetas

**Comment by beatrizSO** [comment]
**Como** desenvolvedor
**Quero** receber os dados
**Para** cadastrar novas camisetas

Criterios de aceitação:

- [ ] Deve receber os dados vindos da Raspberry PI;
- [ ] Deve permitir criar novos itens no banco de dados quando forem produtos diferentes ou somatizar a quantidade de itens iguais;
